apiVersion: v1
kind: Service
metadata:
  name: tcp-single-service-31000
  annotations:
    metallb.universe.tf/address-pool: mlb-pool
spec:
  selector:
    app: myapp
  ports:
    - port: 31000
      targetPort: 31000
      protocol: TCP
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 10.10.0.2