apiVersion: v1
kind: Service
metadata:
  name: tcp-single-service-31000
  annotations:
    metallb.universe.tf/address-pool: mlb-pool
    metallb.universe.tf/allow-shared-ip: "shared-ip-common-value"
spec:
  selector:
    app: myapp
  ports:
    - port: 31000
      targetPort: 31000
      protocol: TCP
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 10.10.0.2
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-single-service-32000
  annotations:
    metallb.universe.tf/address-pool: mlb-pool
    metallb.universe.tf/allow-shared-ip: "shared-ip-common-value"
spec:
  selector:
    app: myotherapp
  ports:
    - port: 32000
      targetPort: 32000
      protocol: TCP
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 10.10.0.2